spring.application.name=school

# Настройки Spring Boot
#  Для messages.properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# application.properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Подключаем СУБД PostgreSQL
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password=chocolatefrog
# Отображать в консоли выполнение скриптов SQL
spring.jpa.show-sql=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= validate

path.to.avatars.folder= /avatars

logging.level.root=DEBUG
server.port=8080
spring.thymeleaf.check-template-location=false
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
