spring.application.name=school

# Настройки Spring Boot
#  Для messages.properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Подключаем СУБД PostgreSQL
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password=chocolatefrog
# Отображать в консоли выполнение скриптов SQL
spring.jpa.show-sql=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
