CREATE TABLE public.users (
                              id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              "name" varchar(16) NOT NULL,
                              driver_license bool NULL,
                              CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE public.auto (
                             id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             brand varchar(16) NOT NULL,
                             model varchar(16) NOT NULL,
                             price numeric(19, 2) NOT NULL,
                             CONSTRAINT auto_pk PRIMARY KEY (id),
                             CONSTRAINT auto_unique UNIQUE (brand,model)
);

CREATE TABLE public.users_auto_link (
                                        user_id int4 NOT NULL,
                                        auto_id int4 NOT NULL,
                                        CONSTRAINT users_auto_link_auto_fk FOREIGN KEY (auto_id) REFERENCES public.auto(id) ON DELETE CASCADE,
                                        CONSTRAINT users_auto_link_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX users_auto_link_user_id_idx ON public.users_auto_link USING btree (user_id, auto_id);